foreground         #c4c7cc
background         #161f34
background_opacity 1.0
cursor             #c4c7cc

active_tab_foreground     #161f34
active_tab_background     #c4c7cc
inactive_tab_foreground   #c4c7cc
inactive_tab_background   #161f34

active_border_color   #c4c7cc
inactive_border_color #161f34
bell_border_color     #0f4e6c

color0       #161f34
color8       #656c7c
color1       #0f4e6c
color9       #146891
color2       #405a6b
color10      #56788F
color3       #296484
color11      #3786B0
color4       #54666c
color12      #718891
color5       #416c84
color13      #5790B0
color6       #4d7a92
color14      #67A3C3
color7       #979aa1
color15      #c4c7cc
